### ISSUE TITLE
Unable to set initial color dynamically

### ISSUE THREAD

**Issue by fan-boy** [jeslage/react-pick-color#12]
Love the library. Really good color picker for React typescript projects.

However, I realised that I cant change the initial color once the color picker is rendered. 

`  <ColorPicker color={customThemePrimary} hideAlpha onChange={(color) => onChangePrimaryColor(color.hex)} />` 

I'm using the ColorPicker component in the above way. The "customThemePrimary" can be changed through other parts of the app as well. But if it's changed from other parts then it doesn't reflect in the ColorPicker component. The ColorPicker component continues to show the old color. On re-rendering it shows the new color. i.e if I close and open the modal popup that contains the ColorPicker.

**Comment by jeslage** [comment]
Hey @fan-boy, thanks for the issue. Nice to hear that you like the library 👍 
Seems that a `useEffect` hook is missing which updates the internal state if the color prop changes. I will look into this asap and will let you know when the new release is published.

**Comment by fan-boy** [comment]
thanks @jeslage

**Comment by jeslage** [comment]
@fan-boy I recently published a new release which should solve this issue. Just install the version `1.0.1`.
If there's anything else, let me know!
