### ISSUE TITLE
Color sometimes doesn't update until second change

### ISSUE THREAD

**Issue by Pikachews** [jeslage/react-pick-color#13]
Seems the fix for #12 caused some unintentional changes.

### Instructions to Reproduce

1. Open any story in the demo app (https://react-pick-color.vercel.app/)
2. Try to change the color by clicking (not dragging, it's less noticeable).
3. Notice that the color will revert back to the previous color, not changing to the desired color.
4. Click the same color again.
5. Notice that the color changes to the desired color.

**Comment by jeslage** [comment]
Thanks for the issue @Pikachews, that's a really weird behavior. I will look into this!

**Comment by jeslage** [comment]
@Pikachews, I recently published a new release `1.0.2` which should solve this issue.
