### ISSUE TITLE
How can I disable the component?

### ISSUE THREAD

**Issue by VictorPotes** [jeslage/react-pick-color#38]
Is there a way to disable the component when there are some conditions? Thanks

**Comment by jeslage** [comment]
Hey @VictorPotes, currently there is no disabled state of the component. You could dynamically render the whole component to hide it when some conditions are met, but i dont know if that fits your use case.
```
{!isDisabled && <ColorPicker {...props} />
```
Where do you need a disabled state for?

**Comment by jeslage** [comment]
Awesome, looks good aswell!
