### ISSUE TITLE
Saving color presets doesn't work with React 18+ (maybe even 17?)

### ISSUE THREAD

**Issue by Pikachews** [jeslage/react-pick-color#55]
👋 Hi again

I'm trying to use this package for my project, which uses React 18, and I suspect it's due to an incompatibility that I see the following behavior.

With color presets enabled:
Save a new color preset
Hide the color picker
Show the color picker
Saved color preset is no longer present

What I'm suspecting is happening, due to changes to React internals, is that the `localStorage.setItem` is being called before the `localStorage.getItem` in the following code:

```
  useEffect(() => {
    const local = JSON.parse(
      window.localStorage.getItem("rpc-presets") || "[]"
    ) as RgbColor[];

    if (Array.isArray(local)) setLocalColors(local);
  }, []);

  useEffect(() => {
    window.localStorage.setItem("rpc-presets", JSON.stringify(localColors));
  }, [localColors]);
```

I see that the preset color gets saved into localStorage, but when the picker is active again, the saved preset color does not show up and the localStorage value is replaced with the default value `[]`.

**Comment by jeslage** [comment]
Hey, sorry for my late response. I hope I will have time this week to look at this.

**Comment by jeslage** [comment]
Hey @Pikachews, 
I just fixed this issue and published a new version. Updating to `1.0.4` should fix this. Otherwise let me know and I will reopen this issue. :)
