### ISSUE TITLE
Compatibility issue with react-18.*

### ISSUE THREAD

**Issue by MuhammadWaseem0006** [jeslage/react-pick-color#57]
Please upgrade your package to react 18 version.

**Comment by maifumei** [comment]
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-pick-color@1.0.4

Please upgrade your package to react 18 version.

**Comment by jeslage** [comment]
Compatibility with react 18 is added now, please upgrade to version 2.0.0
if there are still issues, just let me know!
